[package]
name = "propagate"
version = "0.1.0"
edition = "2021"
about = "data generation tool"
author = "tobias@tobias.dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
